### ISSUE TITLE
Invalid go version

### ISSUE THREAD

**Issue by japinli** [greenplum-db/gpbackup#386]
In README.md, the __Pre-Requisites__ says it requires [Go Programming language version 1.8 or higher](https://github.com/greenplum-db/gpbackup/blob/master/README.md#pre-requisites), however, I cannot build gpbackup with go 1.9.

When I check the Makefile, and find it use [`go mod`](https://github.com/greenplum-db/gpbackup/blob/master/Makefile#L33) to download go modules. But, the `go mod` is available in [go 1.11 or higher](https://blog.golang.org/using-go-modules).

Maybe, we should change the description of __Pre-Requisites__ to make it more accurately.

**Comment by kyeap-pivotal** [comment]
This is correct! Thanks for pointing out this inconsistency within our README. We will update it accordingly.

**Comment by kyeap-pivotal** [comment]
Fixed with commit c9f1f9a.
