### ISSUE TITLE
go get github.com/greenplum-db/gpbackup fails

### ISSUE THREAD

**Issue by professor** [greenplum-db/gpbackup#39]
Maybe I'm doing something incorrect. I'm following the project's README

```
ls ~/go/bin/src/github.com/greenplum-db
<<nothing in there>>

go get github.com/greenplum-db/gpbackup
can't load package: package github.com/greenplum-db/gpbackup: no buildable Go source files in /Users/pivotal/go/bin/src/github.com/greenplum-db/gpbackup

ls ~/go/bin/src/github.com/greenplum-db
gpbackup 
```

**Comment by chrishajas** [comment]
Nice catch! That's a bit out of date, we'll update it. You now have to run `go get github.com/greenplum-db/gpbackup/...` since we build multiple binaries now.

**Comment by chrishajas** [comment]
Fixed the README in https://github.com/greenplum-db/gpbackup/commit/96c93a381ea9fe3981221c3d03366115f82507e8. Please create another issue if you encounter any other errors in our documentation.
