### ISSUE TITLE
value of distribution key doesn't belong to segment with ID xxx, it belongs to segment with ID xxx 

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#425]
When I restore v1.19.0 the data, I got the error as below. But both clusters have the same number of segments and segment map (contents, dbids).

```bash
[gpadmin@gp6mdw greenplum]$ gprestore --backup-dir /gpbackup/20201019191245 --timestamp 20201019191245 --create-db
20201019:21:27:45 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Restore Key = 20201019191245
20201019:21:27:45 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Creating database
20201019:21:27:51 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Database creation complete for: "F6_BDC"
20201019:21:27:51 gprestore:gpadmin:gp6mdw:011474-[WARNING]:-This backup set was taken on a version of Greenplum prior to 6.x. This restore will use the legacy hash operators when loading data.
20201019:21:27:51 gprestore:gpadmin:gp6mdw:011474-[WARNING]:-To use the new Greenplum 6.x default hash operators, these tables will need to be redistributed.
20201019:21:27:51 gprestore:gpadmin:gp6mdw:011474-[WARNING]:-For more information, refer to the migration guide located as https://docs.greenplum.org/latest/install_guide/migrate.html.
20201019:21:27:51 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Restoring pre-data metadata
Pre-data objects restored:  1826 / 1826 [===========================================] 100.00% 21m56s
20201019:21:49:48 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Pre-data metadata restore complete
Tables restored:  12 / 1492 [>-------------------------------------------------------------]   0.80%20201019:21:51:39 gprestore:gpadmin:gp6mdw:011474-[ERROR]:-Error loading data into table fis.fis2_pca_model: COPY fis2_pca_model, line 1: "1395T0011102,1,XSM,WCxxxx Lexington SCSI SOS Card,0,1,0,20,400,77,14,237278-001,D02 ,XXXX    ,HPQ,Le...": ERROR: value of distribution key doesn't belong to segment with ID 2, it belongs to segment with ID 0  (seg2 10.13.0.23:40002 pid=55527) (SQLSTATE 23000)

20201019:21:51:39 gprestore:gpadmin:gp6mdw:011474-[ERROR]:-Encountered 1 error(s) during table data restore; see log file /home/gpadmin/gpAdminLogs/gprestore_20201019.log for a list of table errors.
20201019:21:51:39 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Data restore complete
20201019:21:51:39 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Restoring post-data metadata
Post-data objects restored:  328 / 328 [=============================================] 100.00% 7m20s
20201019:21:58:59 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Post-data metadata restore complete
20201019:21:58:59 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Found neither /usr/local/greenplum-db-6.11.2/bin/gp_email_contacts.yaml nor /home/gpadmin/gp_email_contacts.yaml
20201019:21:58:59 gprestore:gpadmin:gp6mdw:011474-[INFO]:-Email containing gprestore report /gpbackup/20201019191245/gpseg-1/backups/20201019/20201019191245/gprestore_20201019191245_20201019212745_report will not be sent
```

- fis2_pca_model

```sql
CREATE TABLE fis.fis2_pca_model
(
    model character(12) NOT NULL,
    inuse integer NOT NULL,
    fis_code character(3) NOT NULL,
    ...
    CONSTRAINT fis2_pca_model_pkey PRIMARY KEY (model)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default
DISTRIBUTED BY (model)
;
```

**Comment by cobolbaby** [comment]
How to keep the distribution strategy when upgrading from GP5 to GP6

**Comment by jimmyyih** [comment]
Thanks for reporting this issue.  I am able to reproduce it on my local system.


> How to keep the distribution strategy when upgrading from GP5 to GP6

The `gprestore` utility does this automatically for you by setting the `gp_use_legacy_hashops` session GUC for each connection.  See below code snippet from `restore/wrappers.go:InitializeConnectionPool()`:
```
// If the backup is from a GPDB version less than 6.0,
// we need to use legacy hash operators when restoring
// the tables.
backupConfigMajorVer, _ := strconv.Atoi(strings.Split(backupConfig.DatabaseVersion, ".")[0])
if backupConfigMajorVer < 6 {
        setupQuery += "SET gp_use_legacy_hashops = on;\n"
        gplog.Warn("This backup set was taken on a version of Greenplum prior to 6.x. This restore will use the legacy hash operators when loading data.")
        gplog.Warn("To use the new Greenplum 6.x default hash operators, these tables will need to be redistributed.")
```

Perhaps there is an operator class mismatch for your distribution key `character(12)`.  When your table is created, the distribution key hash operator is `cdbhash_bpchar_ops` (the full legacy hash operator list can be obtained by querying `SELECT opcname FROM pg_opclass WHERE opcname LIKE 'cdbhash_%'`).  The `cdbhash_bpchar_ops` hash operator should be correct though... I'll need to look into the GPDB 6 code to figure out what's going on when the COPY runs.

**Comment by cobolbaby** [comment]
Thank you for your feedback and look forward to identifying the bug as soon as possible.

**Comment by jimmyyih** [comment]
I have submitted a PR against GPDB 6X_STABLE to fix this issue: https://github.com/greenplum-db/gpdb/pull/11005.

Unfortunately, I'm not sure when the next GPDB 6X release will come out.  If this issue is urgent, a possible workaround could be to convert your `character(12)` columns into `varchar(12)` (if you're okay with changing the column type) and then take another backup.

**Comment by cobolbaby** [comment]
Thank you so much.

I can use the existing data for performance testing first, and then do the data integrity verification after the PR is merged.

**Comment by cobolbaby** [comment]
I am curious whether this bug also occurs when using tools such as gpcopy or gpupgrade.

**Comment by jimmyyih** [comment]
For gpcopy, the tool streams the data into a temp table and then does a `INSERT INTO user_table SELECT * FROM temp_table` which basically bypasses anything related to legacy hash distribution key stuff.  The user table created on the destination cluster is created with the new hash operator.

For gpupgrade, data is not moved around so the data remains in the correct segments.  However, it could be possible that new data after upgrading could end up on the wrong segments.  In this case, the user would have to upgrade to the GPDB 6X release containing the fix and redistribute with `ALTER TABLE tableName SET WITH (REORGANIZE=true)` to distribute the new rows into the correct segments.  Note that this only applies to this particular scenario of a table distributed by bpchar using the legacy bpchar hash operator.

**Comment by cobolbaby** [comment]
The bugfix has been verified, close the issue.
