### ISSUE TITLE
Improve upload failure retry mechanism

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#478]
In recent times, `MultipartUpload: upload multipart failed` occurred when doing full database backups. I always adopted a retry strategy to solve them. At present, I need to re-backed up the whole db, instead of a single upload failure, which causes a great waste of resources.　

```
20210110:22:03:50 gpbackup:gpadmin:mdw:000885-[DEBUG]:-COPY mes.trace_components_new_1_prt_trace_components_9 TO PROGRAM 'gzip -c -1 | /usr/local/greenplum-db-5.28.3/bin/gpbackup_s3_plugin backup_data /tmp/20210110200000_s3_backup.yml <SEG_DATA_DIR>/backups/20210110/20210110200000/gpbackup_<SEGID>_20210110200000_78715128.gz' WITH CSV DELIMITER ',' ON SEGMENT IGNORE EXTERNAL PARTITIONS;
20210110:22:04:52 gpbackup:gpadmin:mdw:000885-[CRITICAL]:-ERROR: Error from segment 16: ERROR:  command error message: 20210110:22:04:33 gpbackup_s3_plugin:gpadmin:sdw5:024156-[ERROR]:-MultipartUpload: upload multipart failed (SQLSTATE 22P04)
github.com/greenplum-db/gpbackup/backup.backupDataForAllTables
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/backup/data.go:167
github.com/greenplum-db/gpbackup/backup.backupData
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/backup/backup.go:276
github.com/greenplum-db/gpbackup/backup.DoBackup
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/backup/backup.go:160
main.main.func1
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/gpbackup.go:23
github.com/spf13/cobra.(*Command).execute
        /tmp/build/3e49593f/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830
github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/build/3e49593f/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /tmp/build/3e49593f/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/gpbackup.go:27
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

- version: 1.20

**Comment by jimmyyih** [comment]
Have you tried modifying the `backup_max_concurrent_requests` or `backup_multipart_chunksize` parameters in the s3 plugin config?  Maybe increasing `backup_multipart_chunksize` could solve your issue?

From documentation:
>backup_max_concurrent_requests
    Optional. The segment concurrency level for a file artifact within a single backup/upload request. The default value is set to 6. Use this parameter in conjuction with the gpbackup --jobs flag, to increase your overall backup concurrency. 
    Example: In a 4 node cluster, with 12 segments (3 per node), if the --jobs flag is set to 10, there could be 120 concurrent backup requests. With the backup_max_concurrent_requests parameter set to 6, the total S3 concurrent upload threads during a single backup session would reach 720 (120 x 6). 
    Note: If the upload artifact is 10MB (see backup_multipart_chunksize), the backup_max_concurrent_requests parameter would not take effect since the file is smaller than the chunk size.
>
>backup_multipart_chunksize
    Optional. The file chunk size of the S3 multipart upload request in Megabytes (for example 20MB), Gigabytes (for example 1GB), or bytes (for example 1048576B). The default value is 10MB and the minimum value is 5MB (or 5242880B). Use this parameter along with the --jobs flag and the backup_max_concurrent_requests parameter to fine tune your backups. Set the chunksize based on your individual segment file size. S3 supports upto 10,000 max total partitions for a single file upload.

**Comment by cobolbaby** [comment]
The default chunksize is indeed not very efficient. Appropriately increasing the value will speed up the backup. However, it does not solve the problem of S3 service stability, and it is necessary to retry processing for abnormal requests.

**Comment by jimmyyih** [comment]
Yes, we have seen other users questioning the default chunk size as well.  We might be increasing the default to something bigger in a future release.

As for S3 upload retry, we can consider implementing it.  It's definitely a reasonable feature request.  How often do you notice S3 Service Stability issues?

**Comment by cobolbaby** [comment]
To be clear, the S3 service I am talking about generally refers to object storage that provides S3 protocol support. 

We are currently using Minio to build object storage services, so the stability is not as stable as public cloud service providers, especially during peak traffic periods.

**Comment by kyeap-vmware** [comment]
The s3 plugin now utilizes a custom retryer when an error is encountered. This should help with failures regarding network instability. s3-plugin commit https://github.com/greenplum-db/gpbackup-s3-plugin/commit/7ed84b11f1c196a7c9d0f6a57c835a03a82b00d7. Feel free to open another issue if more issues are observed.

**Comment by cobolbaby** [comment]
@kyeap-vmware The retry mechanism does not work when the error https://github.com/greenplum-db/gpbackup/issues/433 happens.

**Comment by cobolbaby** [comment]
A new problem arises with the above approach, the transaction needs to be rolled back, do I also need to do connectionPool.MustRollback(whichConn) ?

```
[CRITICAL]:-ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)
```
