### ISSUE TITLE
gprestore failed  gpadmin:gpmaster:015116-[CRITICAL]:-Version string empty 

### ISSUE THREAD

**Issue by MichealLJH** [greenplum-db/gpbackup#486]
PostgreSQL 9.4.24 (Greenplum Database 6.10.1 build commit:efba04ce26ebb29b535a255a5e95d1f5ebfde94e Open Source) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Sep 15 2020 03:51:36
I can use the gpbackup tool excute the backup operation,but gprestore can't excute.
[gpadmin@gpmaster go]$  gprestore --backup-dir /home/gpadmin/backup --timestamp 20210201103637
20210201:10:46:00 gprestore:gpadmin:gpmaster:015116-[INFO]:-Restore Key = 20210201103637
20210201:10:46:00 gprestore:gpadmin:gpmaster:015116-[CRITICAL]:-Version string empty
20210201:10:46:00 gprestore:gpadmin:gpmaster:015116-[INFO]:-Found neither /usr/local/greenplum-db-6.10.1/bin/gp_email_contacts.yaml nor /home/gpadmin/gp_email_contacts.yaml
20210201:10:46:00 gprestore:gpadmin:gpmaster:015116-[INFO]:-Email containing gprestore report /home/gpadmin/backup/gpseg-1/backups/20210201/20210201103637/gprestore_20210201103637_20210201104600_report will not be sen

20210201:10:46:00 gprestore:gpadmin:gpmaster:015116-[CRITICAL]:-Version string empty  ---  I don't know what is mean , and why do not restore...

**Comment by jimmyyih** [comment]
Hello.

> 20210201:10:46:00 gprestore:gpadmin:gpmaster:015116-[CRITICAL]:-Version string empty

That seems to be an error message from the Golang semvar package.  We use semvar for validating GPDB versions.  Let's check a couple things.

1. When running gprestore, do you have the GPDB environment sourced (e.g. `source $GPHOME/greenplum_path.sh`)?
2. Could you give the top snippet of the backup config file?
Example:
```
○ → find . -name gpbackup_20210202011951_config.yaml
./demoDataDir-1/backups/20210202/20210202011951/gpbackup_20210202011951_config.yaml

○ → grep -i version ./demoDataDir-1/backups/20210202/20210202011951/gpbackup_20210202011951_config.yaml
backupversion: 1.20.2
databaseversion: 6.11.2+dev.153.gecbaf05e52 build dev
pluginversion: ""
```

For you, it would probably be something like this:
```
cd /home/gpadmin/backup
find . -name gpbackup_20210201103637_config.yaml | xargs grep -i version
```

**Comment by MichealLJH** [comment]
Hello jimmyyih,thks for you reply.
I check the yaml files in the backup_HOME directory，**backupversion: 1.20.2** option is empty;
I change the install method,no longer using networking installation, i used the pkg method installed and backup & restore excuted,the test is normal.
So I think there may be a problem with the way of the GO & Online Install type.  
Thks for your help.
