### ISSUE TITLE
How to specify GreenplumDB host 

### ISSUE THREAD

**Issue by anikin-aa** [greenplum-db/gpbackup#488]
Hi !

I've got a question regarding execution of `gpbackup`/`gprestore`  tools. 

Is it possible to specify greenplumdb host ?

I want to collect and store backup from a different VM, is it possible ?

**Comment by jimmyyih** [comment]
Hello.  If you're talking about simply running gpbackup/gprestore on a different GPDB cluster or the target GPDB cluster is on a different host than the one you're on... you might be able to do it by exporting `PGHOST` and `PGPORT` to the target hostname and port before running gpbackup/gprestore.  Note that the target GPDB cluster must have the same gpbackup/gprestore version installed as the one you're currently running.  Also, some features such as `--single-data-file` may need passwordless ssh permission on all hosts of the target GPDB cluster for the machine that you'll be running gpbackup/gprestore on.  So yes, it's technically possible I would imagine but you could run into some minor hurdles setting things up (e.g. `pg_hba.conf` on target GPDB cluster must be set up properly).  IMO, it's probably better if you just ssh to the target GPDB cluster host and run gpbackup/gprestore from there (the regular way)... or if you really need to then send a command with the ssh (e.g. something like `ssh otherHost "source /usr/local/gpdb/greenplum_path.sh && export PGPORT=5432 && gpbackup --dbname mydb"`).

**Comment by anikin-aa** [comment]
@jimmyyih , thanks for the response, it's very helpful. 

I've also checked source code and found that `PG_HOST` env variable is used for gpdb connection. 

Resolving the issue.
