### ISSUE TITLE
gprestore. Error using options --redirect-schema with --metadata-only together.

### ISSUE THREAD

**Issue by Konstantin-La** [greenplum-db/gpbackup#491]
Hello. When using greenplum 5.28, I encountered unexpected behavior of the gprestore utility version 1.20.1. If both --redirect-schema and --metadata-only are specified together, gprestore will return an error like 
`"gprestore:<user>:<master hostname>:025223-[CRITICAL]:-The following flags may not be specified together: truncate-table, metadata-only, incremental, redirect-schema". `
Checked the same with gprestore version 1.17 (from gpbackup 5.25), it works correctly. Also there are no restrictions on using these options in the documentation ( https://gpdb.docs.pivotal.io/backup-restore/1-20/utility_guide/ref/gprestore.html )
Please tell me if there is a bug or if gprestore has some hidden limitation of using options --redirect-schema with --metadata-only together.

**Comment by jimmyyih** [comment]
Hello,

Yes, this does seem to be a regression introduced in gpbackup version 1.18 when we introduced the `--truncate` flag and updated the gprestore flag combinations validation check.  Thanks for reporting it!  We'll look into it and provide a fix as soon as we can.

- Jimmy

**Comment by jimmyyih** [comment]
Fixed with https://github.com/greenplum-db/gpbackup/commit/24a9122da237a3c0ea4abd6de5762a74f2f763c0.  Thanks for the report!
