### ISSUE TITLE
gpbackup block some irrelevant sql in gpdb6.16.0

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#497]
This week I upgraded my Greenplum cluster from 5.28 to 6.16.0. When I executed gpbackup regularly today, I found that it blocked some SQL, even though these SQLs operate on different tables.

```json
    {
        "datname": "F3_BDC",
        "blocking_clientip": "10.13.0.65",
        "blocking_pid": 40043,
        "current_statement": "COPY report_query.log_query_metadata TO PROGRAM 'gzip -c -1 | /usr/local/greenplum-db-6.16.0/bin/gpbackup_s3_plugin backup_data /tmp/20210509203413_s3_backup.yml /backups/20210509/20210509203413/gpbackup__20210509203413_896693.gz' WITH CSV DELIMITER ',' ON SEGMENT IGNORE EXTERNAL PARTITIONS;",
        "blocked_pid": 47956,
        "blocking_application": "gpbackup_20210509203413",
        "blocked_statement": "TRUNCATE TABLE fis.pca_smt_log_sync",
        "blocked_application": "Kettle",
        "blocked_clientip": "192.168.2.15",
        "blocked_user": "bdcenter",
        "blocking_user": "gpadmin"
    }
```

**Comment by jimmyyih** [comment]
Hello.  Just to be certain, was the table `fis.pca_smt_log_sync` in that backup set?  The gpbackup utility will take an ACCESS SHARE LOCK at the beginning on all tables that will be backed up and will only drop the lock at the end (although we could make some optimizations there maybe to drop the lock after the table data is copied out).  I don't think the `current_statement` is blocking the TRUNCATE but the `blocking_pid 40043` is probably the one holding the ACCESS SHARE lock for the `fis.pca_smt_log_sync` table.  However, there shouldn't be a difference between GPDB 5 and 6 for this scenario.  Could you check the `pg_locks` view next time this happens to see what is blocking the TRUNCATE?

**Comment by cobolbaby** [comment]
The root cause of request blocking is that the resource queue accumulates.
