### ISSUE TITLE
Showing dtabase name in `gpbackup_manager delete-backup`

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpbackup#516]
Hi, Team,

In enterprise version of gpbackup, deleting backup with [`gpbackup_manager delete-backup`](https://gpdb.docs.pivotal.io/backup-restore/1-20/utility_guide/ref/gpbackup_manager.html) only shows backup label, which may cause users accidentally deleted backup files of other database resided in the same cluster.

Maybe your team can consider to improve it by displaying the corresponding database.

Regards.

**Comment by jimmyyih** [comment]
This is not the correct place to ask for this feature request as this repository is for the open source gpbackup (and the open source S3 plugin).  Would suggest sending this commercial feature request to VMware Tanzu support instead where it'll reach the product manager(s) for the closed source product.  FWIW, I'll try to give a mention but it most likely won't be considered unless it goes through VMware Tanzu support as an official customer feature request.
