### ISSUE TITLE
Supporting data restoration to another GPDB cluster with different configuration.

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpbackup#535]
Hi, Team,

Is it possible to make `gprestore` to support data restoration through `mdw` node?

Or maybe restoring data through `gpfdist` utility when the target GPDB cluster is not in the same configuration with the original cluster?

Usually users only hope to restore some data to another cluster for testing use.

But the current `gpbackup` and `gprestore` only allows backup/restore from/to GPDB with the same segment configuration, as [mentioned in the documentation](https://gpdb.docs.pivotal.io/backup-restore/1-22/admin_guide/managing/backup-gpbackup.html#topic_vh5_1hd_tbb).

> A backup created with gpbackup can only be restored to a Greenplum Database cluster with the same number of segment instances as the source cluster. If you run gpexpand to add segments to the cluster, backups you made before starting the expand cannot be restored after the expansion has completed.

In the legacy backup utility `gpcrondump`, backup files can be restored to a GPDB cluster with different segment configuration by feeding backup files through `mdw`.

So it would be helpful to make `gprestore` supports similar functionality.

Regards.

**Comment by jimmyyih** [comment]
Yeah, different-sized cluster restore has been a pretty big topic for a while already and is one of the most highly-requested features.  See the current dev discussion thread here: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/UxDLiDd3AMo.  Feel free to add your thoughts/opinions there as well.  Any community input is valuable.

**Comment by khuddlefish** [comment]
We now support the resize cluster option
