### ISSUE TITLE
value of distribution key doesn't belong to segment with ID 9, it belongs to segment with ID 10 when backup in greenplum 5.28.0 and restore in greenplum 6.20.1

### ISSUE THREAD

**Issue by Breeze0806** [greenplum-db/gpbackup#552]
I use gpbakup 1.23 to backup data in **greenplum 5.28.0** and use gprestore 1.23 to restore data in **greenplum 6.20.1**. Both clusters have the same number of segments.I got the error **"value of distribution key doesn't belong to segment with ID 9, it belongs to segment with ID 10"** like [#425](https://github.com/greenplum-db/gpbackup/issues/425).

my table:
```
create table imp_req_lib(
       imp_id CHARACTER(6) default  '' not null,
       imp_type  CHARACTER(1) default  '' not null,
       imp_state  CHARACTER(1) default  '' not null,
       ......
)  DISTRIBUTED BY (imp_id );
```

my data : 
` ('I01238','0','0',........)`

How can I resovle this problem? Should I upgrade 5.28.0 to newest 5.x like 5.28.12? Thanks for help.

**Comment by oakbarrett** [comment]
Hi @Breeze0806 

Did you use gpbackup/gprestore for the backup/restore of table DDL?    GPDB 5.x and 6.x have different hashing algorithms, and there are specific steps required to restore GPDB 5.x to GPDB 6.x, and gprestore helps with this process.

**Comment by Breeze0806** [comment]
Thanks for your reply. It is very hlepful to me. I get error "role "xxx" does not exist" like #485 when using gprestore for the restore of table DDL,  so I execute table DDL directly by using command "psql -f xxx.sql". Maybe I should try gprestore  with --on-error-continue instand of it.
