### ISSUE TITLE
How to view the execution history of gpbackup

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#565]
I would like to log the state of backups to the monitoring system, and wonder if there is a system view that returns information similar to what gpbackup_manager shows.

**Comment by oakbarrett** [comment]
Hi @cobolbaby , 

The data gpbackup_manager displays is not contained within the Greenplum Database as rows in a table, so there isn't a system view that would return this information.  You could write some type of script to parse the $MASTER_DATA_DIRECTORY/gpbackup_history.yaml file to get the information you want to import into your monitoring system.
