### ISSUE TITLE
Incremental backup of heap tables

### ISSUE THREAD

**Issue by QAQQL** [greenplum-db/gpbackup#623]
Hello, I heard that you are developing incremental backup of heap tables. How is the progress?

**Comment by oakbarrett** [comment]
@QAQQL Hello, unfortunately this feature is not under current development.  There is a constraint on the server side in how the data blocks store data. (and how those blocks are reused upon deletes, etc..)    The characteristics are much different than AO storage, making it impractical for gpbackup to incrementally backup heap tables.

**Comment by QAQQL** [comment]
All right. Well, thank you for the information.
