### ISSUE TITLE
Is it possible to restore from a failed backup

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#633]
When using gpbackup to back up the database, it was interrupted due to some hardware reasons. But many tables had been backed up before the interruption, including table A. Because of some misuse, I had to restore table A, but don't know if it's possible to restore from this ultimately failed backup.

```
20230402205009:
total 5420
-rw-r--r-- 1 gpadmin gpadmin 5479625 Apr  2 20:50 gpbackup_20230402205009_metadata.sql
-rwxr-xr-x 1 gpadmin gpadmin    2160 Apr  2 21:09 gpbackup_20230402205009_report
-rwxr-xr-x 1 gpadmin gpadmin   64645 Apr  2 21:09 gpbackup_20230402205009_config.yaml
```

Failed backups don't generate a TOC file, which seems to be necessary for data restoration. How do I generate a TOC file for a failed backup?

**Comment by oakbarrett** [comment]
@cobolbaby since the backup wasn't completed succesfully, gpbackup can't guarantee the metadata files are complete. 

you could manually read the gpbackup_20230402205009_metadata.sql file, and copy/paste the relevant DDL you are looking to restore via psql

**Comment by cobolbaby** [comment]
>  copy/paste the relevant DDL you are looking to restore via psql

I wanna restore the data of table A.

**Comment by oakbarrett** [comment]
It would be extremely difficult and error prone to manually create a TOC file. 

here is an excerpt from a TOC files: 


```
[gpadmin@gpdb 20230419095750]$ head gpbackup_0_20230419095750_toc.yaml
dataentries:
  149967:
    startbyte: 0
    endbyte: 468863
  149970:
    startbyte: 468863
    endbyte: 937385
  149973:
    startbyte: 937385
    endbyte: 1405980

```


You would need to know the # of rows, the byte size of the data in those rows, etc... to accurately determine the TOC. 


The two options that come to mind: 

1.   do not use the --single-data-file flag.  this will create a single file for each table, and not rely on a TOC. 
2. manually look at the data, and try to determine where table A's data ends, and Table B's data begins.   Depending on the # of columns, data types, etc... in those two tables... its plausible to find that last record...   You could also count the records per segment, and use that as a starting point to find the data. 

something like this could help: 
```

2500=# select gp_segment_id, count(*) from table_a group by 1 order by 1;
 gp_segment_id | count
---------------+-------
             0 | 50133
             1 | 49867
(2 rows)

2500=#
```

**Comment by cobolbaby** [comment]
> do not use the --single-data-file flag. this will create a single file for each table, and not rely on a TOC.

I didn't use the `--single-data-file` option, but it seems that restoring a single table still needs to rely on TOC.

![2023-04-21 11-04-26屏幕截图](https://user-images.githubusercontent.com/11460848/233530826-2ad4b664-292e-4b61-a4f8-e0cf8312e010.png)

My backup command is as follows:

```
    /usr/local/greenplum-db/bin/gpbackup \
        --dbname ${db} \
        --plugin-config /opt/greenplum/config/gpbackup_s3_backup.yml \
        --exclude-table-file /opt/greenplum/config/gpbackup_exclude_table \
        --leaf-partition-data \
        --with-stats \
        --jobs 4 --quiet
```

**Comment by cobolbaby** [comment]
> You would need to know the # of rows, the byte size of the data in those rows, etc... to accurately determine the TOC.

The # of rows, the byte size of the data is not easy to obtain accurately, because I can't know that at the backup time point. And I can't go back to the past.

**Comment by oakbarrett** [comment]
the TOC file is written at the end of a backup.  If the backup fails midway, this file is not written. 

If you are confident table A's data is complete, and written to the data file, you can find all the corresponding tableA data files, based on OID in the filename, and run a COPY command on MDW to load the data files, and they are simply .csv

This is the simplest and most straightforward way. 

gprestore can not restore an incomplete backup set due to backup failure/quiting/etc..
