### ISSUE TITLE
Can gpbackup/gprestore be deployed independently, and back up the database by remote calling?

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#634]
It will be much more convenient to debug gpbackup/gprestore if the database is backed up by remote calling.

such as: 

```
gpbackup --host ??? --port ??? --dbname demo --username ??? --plugin-config /opt/greenplum/config/s3_backup.yml --metadata-only
``` 

or 

```
export PGHOST=
export PGPORT=
export PGUSER=
export PGPASSWORD=
gpbackup --dbname demo --plugin-config /opt/greenplum/config/s3_backup.yml --metadata-only
```

**Comment by oakbarrett** [comment]
Hi @cobolbaby 
Thanks for your input, at this time there are no plans to create a client side version of gpbackup (similar to psql). 

One alternative is to use ssh from your client: 

`oak_laptop:~ obarrett$ ssh gpadmin@gpdb "gpbackup --dbname gpadmin";
20230405:09:44:15 gpbackup:gpadmin:gpdb:079474-[INFO]:-gpbackup version = 1.27.0+dev.21.g63133a1
20230405:09:44:15 gpbackup:gpadmin:gpdb:079474-[INFO]:-Greenplum Database Version = 6.21.0 build commit:d0087e3b24c54d203ca8bb315559205f13cd6393
20230405:09:44:15 gpbackup:gpadmin:gpdb:079474-[INFO]:-Starting backup of database gpadmin
20230405:09:44:15 gpbackup:gpadmin:gpdb:079474-[INFO]:-Backup Timestamp = 20230405094415
20230405:09:44:15 gpbackup:gpadmin:gpdb:079474-[INFO]:-Backup Database = gpadmin
20230405:09:44:15 gpbackup:gpadmin:gpdb:079474-[INFO]:-Gathering table state information
20230405:09:44:15 gpbackup:gpadmin:gpdb:079474-[INFO]:-Acquiring ACCESS SHARE locks on tables
Locks acquired:  2 / 2  100.00% 0s
20230405:09:44:15 gpbackup:gpadmin:gpdb:079474-[INFO]:-Gathering additional table metadata
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Getting partition definitions
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Getting storage information
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Getting child partitions with altered schema
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Metadata will be written to /gpmaster6/gp6-1/backups/20230405/20230405094415/gpbackup_20230405094415_metadata.sql
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Writing global database metadata
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Global database metadata backup complete
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Writing pre-data metadata
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Pre-data metadata metadata backup complete
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Writing post-data metadata
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Post-data metadata backup complete
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Writing data to file
Tables backed up:  2 / 2  100.00% 0s
20230405:09:44:16 gpbackup:gpadmin:gpdb:079474-[INFO]:-Data backup complete
20230405:09:44:17 gpbackup:gpadmin:gpdb:079474-[INFO]:-Found neither /usr/local/greenplum-db-6.21.0/bin/gp_email_contacts.yaml nor /home/gpadmin/gp_email_contacts.yaml
20230405:09:44:17 gpbackup:gpadmin:gpdb:079474-[INFO]:-Email containing gpbackup report /gpmaster6/gp6-1/backups/20230405/20230405094415/gpbackup_20230405094415_report will not be sent
20230405:09:44:17 gpbackup:gpadmin:gpdb:079474-[INFO]:-Backup completed successfully
oakbSJGH5:~ obarrett$
`

**Comment by cobolbaby** [comment]
Do you always use remote debugging when developing?
