### ISSUE TITLE
Gprestore v1.28.1 fails with error GLIBC_2.28 not found

### ISSUE THREAD

**Issue by baileygm** [greenplum-db/gpbackup#650]
Gprestore using version 1.28.1 fails with the following error

```gprestore: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by gprestore)```

After reverting back to version 1.27.0 the restore ran succesfully

Greenplum version 6.24.0 is running in a docker container built using `ubuntu:bionic-20230308`
Gpbackup binaries are built using `golang:1.19-buster`

**Comment by AJR-VMware** [comment]
Hi @baileygm ,

Did you build the gpbackup binaries on an ubuntu:bionic platform?

**Comment by baileygm** [comment]
I built them within a golang:1.19-buster docker container and then copied them into the ubuntu:bionic-20230308 where I installed Greenplum

**Comment by AJR-VMware** [comment]
Looks like `ubuntu:bionic-20230308` only has GLIBC 2.27, while `golang:1.19-buster` has GLIBC 2.28.  This explains why gprestore is looking for `2.28` and not finding it.  You'll need to build on a compatible platform.

**Comment by khuddlefish** [comment]
We recently introduced https://github.com/mattn/go-sqlite3 which is a C-go library so gpbackup now needs to be built on the platform it will be run on. The `golang:1.19-buster` buster image is based on alpine so it will not be compatible with ubuntu. Please try rebuilding on an `ubuntu:bionic` image.

**Comment by baileygm** [comment]
> Looks like `ubuntu:bionic-20230308` only has GLIBC 2.27, while `golang:1.19-buster` has GLIBC 2.28. This explains why gprestore is looking for `2.28` and not finding it. You'll need to build on a compatible platform.

I don't doubt that you are correct but I used exactly the same build process for gpbackup 1.27.0 and 1.28.1 and the 1.27.0 image worked and the 1.28.1 failed

Is there any login in that ?

**Comment by baileygm** [comment]
I'll try that thanks

**Comment by AJR-VMware** [comment]
I'll leave the issue open for a bit in case there are any follow-ups.  Thanks for reaching out!

**Comment by baileygm** [comment]
Thanks @AJR-VMware and @khuddlefish 
Building gpbackup using ubuntu fixed the issue and backup/restore is now running fine
Exemplary support as ever
