### ISSUE TITLE
Anywhy to use gpbackup will multiple paths.

### ISSUE THREAD

**Issue by greenplumdba** [greenplum-db/gpbackup#670]
Anywhy to use gpbackup will multiple paths.

I want to use gpbackup to unload on two nas Server location

Current backup utility accept only one parameter. 

Use case is unique :) 

Ex.
Segment host 1 will push 
the data to /nfs/bkp_data1
the data to /nfs/bkp_data2

If 8 segment host are their i will be using 16 NAS location with different IP's. To boost performance.

**Comment by oakbarrett** [comment]
Hi @greenplumdba this scenario is currently not supported.  The recommended alternative is to run multiple backups (perhaps split up by --include-shema or --include-table filters), each pointing to different NFS location.
