### ISSUE TITLE
gpbackup 1.29 cannot handle gpdb6 some inherit table successfully

### ISSUE THREAD

**Issue by xiaoxiaoHe-E** [greenplum-db/gpbackup#679]
step to reproduce:
GPDB version: gp6 and gp7
1. create tables
```
CREATE TABLE foo(a int);
CREATE TABLE too(b int);
CREATE TABLE footoo() INHERITS(foo,too);
```

2. call gpbackup 1.29
```
gpbackup --dbname testdb_gpcopy_ginkgo1 --backup-dir /tmp/gpcopy_dump --metadata-only --no-history --include-table "public"."foo"
```
3. dump result:
```
SET client_encoding = 'UTF8';


CREATE TABLE public.foo (
        a integer
) DISTRIBUTED BY (a);


ALTER TABLE public.foo OWNER TO gpadmin;


CREATE TABLE public.too (
        b integer
) DISTRIBUTED BY (b);


ALTER TABLE public.too OWNER TO gpadmin;


CREATE TABLE public.footoo (
        a integer,
        b integer
) INHERITS (public.foo, public.too) DISTRIBUTED BY (a);


ALTER TABLE public.footoo OWNER TO gpadmin;
```

For this case, only gpbackup 1.28 working on gpdb6 has the right result, which only creates table foo.

I mentioned this problem in this [issue](https://github.com/greenplum-db/gpbackup/issues/614#issuecomment-1451432257) before, it only fails in gpdb7.  But this time in gpbackup 1.29, gpdb6 has the same problem.

We would like to suggest that you may add a test for this case to avoid such failure in future releases.

**Comment by jmcatamney** [comment]
We modified gpbackup's inclusion criteria and introduced the `--no-inherits` flag in 1.29, as mentioned in the release notes, in order to unify the behavior between 6 and 7.  If you pass that flag when running a backup in this scenario, only `foo` will be backed up.
