### ISSUE TITLE
gprestore do not create roles with a gp_ prefix in gpdb7

### ISSUE THREAD

**Issue by ycauld** [greenplum-db/gpbackup#680]
gprestore does not create any role with a prefix of gp_.  GPDB7 beta 4 allows roles with a prefix of gp_ and the create role works correctly.  a pg_dumpall -r will correctly create a gp_ role.

**Comment by oakbarrett** [comment]
thank you @ycauld for pointing this out.  We will take a look and get this resolved.

**Comment by oakbarrett** [comment]
@ycauld 

We could not reproduce your issue.  Could you please provide the backup and restore commands used. 

- I created a new ROLE:   gp_testrole
- took a gpbackup
- dropped the role from the database
- ran gprestore  --with-globals and --on-error-continue, and the role was created succesfully.
