### ISSUE TITLE
gpbackup 1.29.0 reports wrong end time and duration

### ISSUE THREAD

**Issue by Immerh** [greenplum-db/gpbackup#685]
The end time in Greenplum Database Backup Report shows the time when 'Writing global database metadata' is written on the console.
I expected the time corresponding to 'Data backup complete'.

**Comment by oakbarrett** [comment]
Thanks @Immerh , we will get this fixed

**Comment by oakbarrett** [comment]
gpbackup v1.29.2
Resolved Issue

Resolves an issue where gpbackup was reporting the incorrect end timestamp in the report file.

https://docs.vmware.com/en/VMware-Greenplum-Backup-and-Restore/1.29/greenplum-backup-and-restore/release-notes.html
