### ISSUE TITLE
gprestore error  with --resize-cluster 32 seg to 16 seg

### ISSUE THREAD

**Issue by joyful88** [greenplum-db/gpbackup#705]
old version GP 6.24.2 new version 6.25.1
I have a backup taken from 32 segments. I want to deploy it on 16 segments, but when specifying the --resize-cluster key, an error occurs:
backup.config.yaml

backupdir: /mounttest/sigma_p
backupversion: 1.28.1
compressed: true
compressiontype: zstd
databasename: sigma_p
databaseversion: 6.24.2 build commit:2605b114ee5662dc6d972568ce50961fae74c69a Open
  Source
segmentcount: 32

and restore command:
gprestore --backup-dir /mounttest/sigma_p/ --timestamp 20230817093454 --resize-cluster --create-db
with error:
Creating database
20230818:09:06:43 gprestore:gpadmin:dl-gp-m01:004502-[INFO]:-Database creation complete for: sigma_p
20230818:09:06:43 gprestore:gpadmin:dl-gp-m01:004502-[INFO]:-Restoring pre-data metadata
Pre-data objects restored:  761 / 761 [================================================] 100.00% 16s
20230818:09:07:00 gprestore:gpadmin:dl-gp-m01:004502-[INFO]:-Pre-data metadata restore complete
20230818:09:07:00 gprestore:gpadmin:dl-gp-m01:004502-[CRITICAL]:-Found incorrect number of backup files on 16 segments. See /home/gpadmin/gpAdminLogs/gprestore_20230818.log for a complete list of errors.

in file /home/gpadmin/gpAdminLogs/gprestore_20230818.log 

20230818:07:59:27 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  10% (77/761)
20230818:07:59:28 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  20% (153/761)
20230818:07:59:30 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  30% (229/761)
20230818:07:59:31 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  40% (305/761)
20230818:07:59:34 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  50% (381/761)
20230818:07:59:35 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  60% (457/761)
20230818:07:59:37 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  70% (533/761)
20230818:07:59:39 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  80% (609/761)
20230818:07:59:40 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  90% (685/761)
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Pre-data objects restored:  100% (761/761)
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[INFO]:-Pre-data metadata restore complete
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Verifying backup file count
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 0 on host dl-gp-n01, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 1 on host dl-gp-n01, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 2 on host dl-gp-n01, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 3 on host dl-gp-n01, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 4 on host dl-gp-n02, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 5 on host dl-gp-n02, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 6 on host dl-gp-n02, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 7 on host dl-gp-n02, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 8 on host dl-gp-n03, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 9 on host dl-gp-n03, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 10 on host dl-gp-n03, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 11 on host dl-gp-n03, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 12 on host dl-gp-n04, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 13 on host dl-gp-n04, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 14 on host dl-gp-n04, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Expected to find 132 file(s) on segment 15 on host dl-gp-n04, but found 66 instead.
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[CRITICAL]:-Found incorrect number of backup files on 16 segments. See /home/gpadmin/gpAdminLogs/gprestore_20230818.log for a complete list of errors.
github.com/greenplum-db/gp-common-go-libs/cluster.LogFatalClusterError
	/tmp/build/dfde230c/go/pkg/mod/github.com/greenplum-db/gp-common-go-libs@v1.0.12/cluster/cluster.go:412
github.com/greenplum-db/gpbackup/restore.VerifyBackupFileCountOnSegments
	/tmp/build/dfde230c/go/src/github.com/greenplum-db/gpbackup/restore/remote.go:72
github.com/greenplum-db/gpbackup/restore.DoRestore
	/tmp/build/dfde230c/go/src/github.com/greenplum-db/gpbackup/restore/restore.go:160
main.main.func1
	/tmp/build/dfde230c/go/src/github.com/greenplum-db/gpbackup/gprestore.go:23
github.com/spf13/cobra.(*Command).execute
	/tmp/build/dfde230c/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920
github.com/spf13/cobra.(*Command).ExecuteC
	/tmp/build/dfde230c/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	/tmp/build/dfde230c/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	/tmp/build/dfde230c/go/src/github.com/greenplum-db/gpbackup/gprestore.go:27
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[INFO]:-Found neither /usr/local/greenplum-db-6.25.1/bin/gp_email_contacts.yaml nor /home/gpadmin/gp_email_contacts.yaml
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[INFO]:-Email containing gprestore report /mounttest/sigma_p/gpseg-1/backups/20230817/20230817093454/gprestore_20230817093454_20230818075925_report will not be sent
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Beginning cleanup
20230818:07:59:42 gprestore:gpadmin:dl-gp-m01:000984-[DEBUG]:-Cleanup complete

**Comment by oakbarrett** [comment]
@joyful88 

the current beta version of --resize-cluster, when used with the --backup-dir flag, requires you to manually move the files into the correct directories.   i.e.  seg16 files need to be move to seg0, seg17 to seg1, seg18 to seg2, etc..  

if using a --plugin-config based backup, this limitation is not there.

the next feature release of gpbackup 1.30.0  will eliminate the issue you are seeing in the beta version
